// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using backend.Entities;

#nullable disable

namespace backend.DbContext
{
    public partial class LedblinkerContext : Microsoft.EntityFrameworkCore.DbContext 
    {
        public LedblinkerContext()
        {
        }

        public LedblinkerContext(DbContextOptions<LedblinkerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Commands> Commands { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}