// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class Commands
    {
        public int id { get; set; }
        public bool left_value { get; set; }
        public bool right_value { get; set; }
        public bool valid { get; set; }
    }
}